DOP-3571: Add README.md
mongodb/docs-search-transport pull request #34
Opened 2023-04-04 18:00 UTC by casthewiz

Adds a barebones README.md file to the repository. 
Additional testing details to come as we setup CI.

2023-04-07 14:05 UTC, seungpark requested changes
LGTM! very informative. can we add an overview of this module below the first heading?

ie `REST server that manages search documents within an Atlas cluster and handles user search requests, deployed via Kanopy drones`

2023-04-07 14:05 UTC, seungpark commented on README.md
> +New release tags automatically begain deployment via Kanopy to production instances.
minor typo. "begin"

2023-04-07 15:42 UTC, casthewiz commented
Haha, that would indeed be good to add!

2023-04-10 15:25 UTC, seungpark approved these changes
LGTM! much thanks for adding dotenv! 🙏

2023-04-10 21:29 UTC, merged