DOCSP-31491: update synonym file
mongodb/docs-search-transport pull request #58
Opened 2023-08-01 15:28 UTC by sarahemlin

@casthewiz -

I added synonyms for searches with zero results and a few others I've been collecting.  If this process works, let me know who else could approve PRs for the synonym file going forward.

Thanks!
Sarah

2023-08-01 21:27 UTC, casthewiz approved these changes
This LGTM - in the future, feel free to request @seungpark or @branberry as reviewers also.

(And feel free to merge on a single approval).

We'll be able to observe the results in staging post-merge, and make additional changes if we need to.

2023-08-01 22:06 UTC, seungpark requested changes
caught a few minor repeated synonyms! PTAL @sarahemlin

2023-08-01 22:06 UTC, seungpark commented on resources/synonyms.csv
> +operator,$$,dollar sign,
```suggestion
operator,$,$$,dollar sign,

```

we can remove line 21 after

2023-08-01 22:06 UTC, seungpark commented on resources/synonyms.csv
> +mongosh,shell,mongo shell,mongodb shell,
similar here with line 17

2023-08-01 22:06 UTC, seungpark commented on resources/synonyms.csv
> +ne,not equal,
this can be merged with line 20

2023-08-03 17:10 UTC, seungpark requested changes
@sarahemlin i left some suggestions. the row numbers were getting mixed up with commits

2023-08-03 17:10 UTC, seungpark commented on resources/synonyms.csv
> +$ne,$neq,not equal,
```suggestion
$ne,$neq,not equal,ne,not equal,
```

2023-08-03 17:10 UTC, seungpark commented on resources/synonyms.csv
> +ne,not equal,
```suggestion
```

2023-08-03 17:10 UTC, seungpark commented on resources/synonyms.csv
>  shell,mongosh,
```suggestion
shell,mongosh,mongo shell,mongodb shell,
```

2023-08-03 17:10 UTC, seungpark commented on resources/synonyms.csv
> +mongosh,shell,mongo shell,mongodb shell,
```suggestion

```

2023-08-03 17:10 UTC, seungpark commented on resources/synonyms.csv
> +
```suggestion

```

2023-08-03 21:14 UTC, seungpark approved these changes
LGTM 👍

2023-08-04 14:44 UTC, seungpark commented
@sarahemlin i deleted an old remnant NULL entry. i think this may have been a remnant of previous commits. will drop in a ticket to refresh the table to prevent this error. we're good to merge!

2023-08-04 14:47 UTC, merged